### ISSUE TITLE
Game crashed after letting 3 AI play alone (without building my castle)

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#120]
[b210m3ai3gm1s2.zip](https://github.com/Pyrdacor/freeserf.net/files/5653909/b210m3ai3gm1s2.zip)
The game crashed with the following output, few minutes after loading above savegame (in the first run, in the second run it seemed to develop differently without crashing [yet]).

> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other
memory is corrupt.
   at Silk.NET.OpenGL.X2A1665C0.GL.DrawElements(Silk.NET.OpenGL.PrimitiveType, UInt32, Silk.NET.OpenGL.DrawElementsType, Void*)
   at Freeserf.Renderer.RenderBuffer.Render()
   at Freeserf.Renderer.RenderLayer.Render()
   at Freeserf.GameView.Render()
   at Freeserf.MainWindow.MainWindow_Render(Double)
   at Silk.NET.Windowing.Desktop.GlfwWindow.RaiseRenderFrame()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(System.Action)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(Silk.NET.Windowing.Common.IView)
   at Silk.NET.Window.Window.Run()
   at Freeserf.Program.Main(System.String[])

**Comment by Pyrdacor** [comment]
Looks like a rendering issue deep down the render pipeline. Maybe only reproducible with your hardware. But I will at least try to catch such issues and let the game progress if possible. Maybe this is only one render frame which must be discarded. That wouldn't hurt much.

I also plan autosaving and a "save on crash" functionality. This won't help for every issue but for such crashes it will.
