### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#161]
The game crashes on startup if I tell it to use the Amiga files. (either prefer or force)

It's a bit random. It did run once with Amiga music and DOS sound, but then never again. 
When it loads, it opens a plain white window, plays the first note of the music, then exits. 

These are the errors I get:

D:\games\Freeserf.net>FreeserfNet.exe
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Freeserf.MainWindow.MainWindow_Update(Double)
   at Silk.NET.Windowing.Desktop.GlfwWindow.RaiseUpdateFrame()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoUpdate()
   at Silk.NET.Windowing.Common.WindowExtensions+<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(System.Action)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(Silk.NET.Windowing.Common.IView)
   at Silk.NET.Window.Window.Run()
   at Freeserf.Program.Main(System.String[])

D:\games\Freeserf.net>FreeserfNet.exe
Fatal error. Internal CLR error. (0x80131506)
   at Silk.NET.OpenGL.X6CDF1A2D.GL.Clear(UInt32)
   at Freeserf.GameView.Render()
   at Freeserf.MainWindow.MainWindow_Render(Double)
   at Silk.NET.Windowing.Desktop.GlfwWindow.RaiseRenderFrame()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoRender()
   at Silk.NET.Windowing.Common.WindowExtensions+<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(System.Action)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(Silk.NET.Windowing.Common.IView)
   at Silk.NET.Window.Window.Run()
   at Freeserf.Program.Main(System.String[])

------------------------------------------------
freeserf.log:
17:42:06 Info: [Data] Looking for game data in 'D:\games\Freeserf.net/music'...
17:42:06 Info: [Data] Looking for game data in 'D:\games\Freeserf.net/SPAE.PA'...
17:42:06 Info: [Data] Looking for game data in 'D:\games\Freeserf.net/sounds'...
17:42:06 Info: [Data] Looking for game data in 'D:\games\Freeserf.net/gfxheader'...
17:42:06 Info: [Data] Looking for game data in 'D:\games\Freeserf.net/gfxfast'...
17:42:06 Info: [Data] Looking for game data in 'D:\games\Freeserf.net/gfxchip'...
17:42:06 Info: [Data] Game data found in 'D:\games\Freeserf.net'...

Even when the game runs with the DOS file, the building graphics are missing.  Is there a particular version that is needed? 
I have SPAE.PA

**Comment by Pyrdacor** [comment]
According to the errors it seems the OpenGL has some issues. It's not about the game data.
