### ISSUE TITLE
Running freeserf.net on Steam Deck

### ISSUE THREAD

**Issue by dos-ise** [Pyrdacor/freeserf.net#163]
I tried running the latest release on my Steam Deck unfortunately it crashed with the following error. 
(See Screenshot)

`Process terminated. Couldn't find a valid ICU package installed on the system.
Set the configuration flag System.Globalization.Invariant to true if you want
to run with no globalization support.   
 at System.Environment.FailFast(System.String)   
 at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
 at System.Globalization.GlobalizationMode..cctor()   
 at System.Globalization.CultureData.CreateCultureWithInvariantData()   
 at System.Globalization.CultureData.get_Invariant()   
 at System.Globalization.CultureInfo..cctor()   
 at System.StringComparer..cctor()   
 at System.StringComparer.get_OrdinalIgnoreCase()   
 at Microsoft.Extensions.Configuration.ConfigurationProvider..ctor()   
 at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
 at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()   
 at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder..ctor(Microsoft.Extensions.Hosting.IHostBuilder)
 at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(Microsoft.Extensions.Hosting.IHostBuilder, System.Action'1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)   
 at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(Microsoft.Extensions.Hosting.IHostBuilder, System.Action'1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)   
 at WebApplication.Program.CreateHostBuilder(System.String[])   
 at WebApplication.Program.Main(System.String[])`

Migrating freeserf.net to NET.8 fixed this issue for me.

So if anyone want to run this amazing project on your steam deck take a look at my fork.

![Screenshot_20241016_084906](https://github.com/user-attachments/assets/c8201be2-203f-41fd-8ac0-f9d8dca0f7e8)
![Screenshot_20241016_090104](https://github.com/user-attachments/assets/5a7fc262-850c-4604-a115-881744aeaef4)

**Comment by dak151** [comment]
Hi, I cannot raise an issue with your build on your github fork, so I will do it here in the hope it's seen.  :)

I am running Linux Mint 22.1 w/ Cinnamon Desktop, kernel 6.8.0-58.

I grabbed your release:
https://github.com/dos-ise/freeserf.net/releases/tag/pre-release
"Freeserf.net-Linux.7z"

The game loads and I get graphics/video and can play the game.

The only issue is there is no audio / sound / music.

Nothing.

In the main "options" the options of 'music', 'sound effects' are set to " - " , clicking this does not change it, and volume is set to zero (0). Using the volume +/- buttons does not change it.

Any ideas?

Cheers,

**Comment by Pyrdacor** [comment]
Maybe you could debug inside this file: https://github.com/dos-ise/freeserf.net/blob/master/Freeserf.Audio/Audio.cs

**Comment by dos-ise** [comment]
> Hi @dos-ise , I cannot raise an issue with your build on your github fork, so I will do it here in the hope it's seen.  :)
> 
> I am running Linux Mint 22.1 w/ Cinnamon Desktop, kernel 6.8.0-58.
> 
> I grabbed your release:
> https://github.com/dos-ise/freeserf.net/releases/tag/pre-release
> "Freeserf.net-Linux.7z"
> 
> The game loads and I get graphics/video and can play the game.
> 
> The only issue is there is no audio / sound / music.
> 
> Nothing.
> 
> In the main "options" the options of 'music', 'sound effects' are set to " - " , clicking this does not change it, and volume is set to zero (0). Using the volume +/- buttons does not change it.
> 
> Any ideas?
> 
> Cheers,
> 
> 

Hi, think you are missing the native binaries for the Sound library. They are not included in my release

You need to copy them to the correct folder.

**Comment by dak151** [comment]
Hi, thank you for the reply,

It says that "Audio is provided by [BASS](http://www.un4seen.com/). The assemblies are contained in the releases but they are for 64-bit systems only." 

so I should have the assemblies,..... unless the native binaries are not this?

What are the native binaries that are required ?   ( Linux Mint 22.1 is based on Ubuntu 24.04. )

**Comment by Pyrdacor** [comment]
I guess it should be those: https://github.com/Pyrdacor/freeserf.net/tree/master/FreeserfNet/bass/linux-x64

Make sure the executable will find them. For example place them in the same directory as the executable or in a system directory for libraries.

**Comment by dak151** [comment]
> I guess it should be those: https://github.com/Pyrdacor/freeserf.net/tree/master/FreeserfNet/bass/linux-x64
> 
> Make sure the executable will find them. For example place them in the same directory as the executable or in a system directory for libraries.


Thanks for the details.
Download files and placed them in the same directory as the binary.

Error:

libbassmidi.so: undefined symbol: BASS_GetVersion


```
username@PC:~/path/to/freeserf.net$ ./FreeserfNet 
./FreeserfNet: symbol lookup error: /home/username/path/to/freeserf.net/libbassmidi.so: undefined symbol: BASS_GetVersion
username@PC:~/path/to/freeserf.net$ 
```



Cheers,

**Comment by dak151** [comment]
Quick update.

From where the binary is located, I used LD_PRELOAD

so

`   LD_PRELOAD=./libbass.so ./FreeserfNet   `

Game loads with sound !

**Comment by Pyrdacor** [comment]
Strange that you need LD_PRELOAD. This means that the executable loads something else instead. I guess after compilation it links the wrong shared object.

**Comment by Pyrdacor** [comment]
Did you use the right configuration when building? You need LinuxDebug or LinuxRelease instead of just Debug or Release.

**Comment by Pyrdacor** [comment]
I merged the open PR so the changes are now also available in this repo. Feel free to add more PRs. Thanks.

**Comment by Pyrdacor** [comment]
I just updated the release scripts and released 2.1.2 with your changes. Can you test if everything works with the new version? Thanks.

**Comment by dak151** [comment]
Downloaded the latest linux binary
https://github.com/Pyrdacor/freeserf.net/releases/download/v2.1.2/Freeserf.net-Linux.tar.gz

Extracted all files and placed them where the game data is locaated.

Ran it, and error.


```
user@PC:~/path/to/freeserf.net$ ./FreeserfNet 
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Freeserf.Program.Main(String[] args)
Aborted (core dumped)
user@PC:~/path/to/freeserf.net$ 
```

Cheers,

**Comment by Pyrdacor** [comment]
Can you download again and check if it works now?

**Comment by dak151** [comment]
> Can you download again and check if it works now?

I downloaded   https://github.com/Pyrdacor/freeserf.net/releases/download/v2.1.2/Freeserf.net-Linux.tar.gz

extracted all the files (FreeserfNet, libbass.so and libbassmidi.so) into where the game data files are, ran ./FreeserfNet
and error.

```
user@PC:~/path/to/freeserf.net$ ./FreeserfNet 
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/home/user/path/to/freeserf.net/Freeserf.Audio.dll'. The system cannot find the file specified.

File name: '/home/user/path/to/freeserf.net/Freeserf.Audio.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Freeserf.Program.Main(String[] args)
Aborted (core dumped)
user@PC:~/path/to/freeserf.net$ 
```


Cheers

**Comment by Pyrdacor** [comment]
Sorry to bother you but can you try again?

**Comment by dak151** [comment]
> Sorry to bother you but can you try again?

Sure, happy to.
Gabbed latest gz file.


Running program with -h switch shows the options.

Just running the program returns to the command line...


```
[user@PC:~/path/to/freeserf.net$ ./FreeserfNet -h
Usage:  [-d NUM] [-f] [-g DATA-PATH] [-h] [-l FILE] [-r RES] [-c] [-o LOG-TYPE] [-x LOG-TYPE]

	-d NUM          Set debug output level
	                NUM: 2 ~ 5
	-f              Run in fullscreen mode.
	-g DATA-PATH    Use specified data directory.
	-h              Show this help text.
	-l FILE         Load saved game.
	-r RES          Set display resolution (e.g. 800x600).
	-c              Log to console window.
	-o LOG-TYPE     Log only messages of the given type.
	                Cannot be used with -x option.
	                LOG-TYPE: None, Config, Data, Game, Map, Render,
	                          Textures, Savegame, Building, Flag, Serf, Player,
	                          Inventory, AI, UI, Audio, Application, Network
	-x LOG-TYPE     Log only messages not of the given type.
	                Cannot be used with -o option.
	                LOG-TYPE: None, Config, Data, Game, Map, Render,
	                          Textures, Savegame, Building, Flag, Serf, Player,
	                          Inventory, AI, UI, Audio, Application, Network

Please report bugs to <robert.schneckenhaus@web.de>
user@PC:~/path/to/freeserf.net$ ./FreeserfNet
user@PC:~/path/to/freeserf.net$ ]
```


If I include the files "libglfw.so.3" and "libSDL2-2.0.so"  from https://github.com/dos-ise/freeserf.net/releases/download/pre-release/Freeserf.net-Linux.7z   the game loads, but I still get no sound (like in my original message).



However, if run dos-ise's
https://github.com/dos-ise/freeserf.net/releases/download/pre-release/Freeserf.net-Linux.7z

with the linux audio from
https://github.com/Pyrdacor/freeserf.net/tree/master/FreeserfNet/bass/linux-x64

the game loads with sound, with no problems. (I don't even have to do a   LD_PRELOAD anymore... )

Cheers,

**Comment by Pyrdacor** [comment]
I managed to setup a small ubuntu distro via WSL. I could reproduce the error. I think bass uses some P/Invoke which involves the libdl.so on Linux. When providing it, it worked for me. I included it in the release. Can you try again with updated version? Still 2.1.2

**Comment by dak151** [comment]
D/Led updated file, game loads with sound / music.  Seems to be fine.

Thank you very much!

**Comment by Pyrdacor** [comment]
Great thanks for testing.

As this is fixed and also the initial issue is resolved, I will close this now.
