### ISSUE TITLE
Error: [FrameTimer] [building]Failed to cancel unrequested resource delivery.

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#30]
[building]Failed to cancel unrequested resource delivery.

========== Stack Trace: ==========

   at Freeserf.Building.CancelTransportedResource(Type res)
   at Freeserf.Game.CancelTransportedResource(Type type, UInt32 dest)
   at Freeserf.Flag.ScheduleSlotToKnownDest(Int32 slot, Int32[] resWaiting)
   at Freeserf.Flag.Update()
   at Freeserf.Game.UpdateFlags()
   at Freeserf.Game.UpdateVisuals()
   at Freeserf.Game.Update()
   at Freeserf.UI.Interface.Update()
   at Freeserf.LocalSpectatorViewer.Update()
   at Freeserf.Renderer.OpenTK.GameView.Render()
   at Freeserf.FreeserfForm.FrameTimer_Tick(Object sender, EventArgs e)
   
[b197-m9-4ai-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/3009632/b197-m9-4ai-saves.zip)

**Comment by Pyrdacor** [comment]
Should be fixed but patch will follow later.

**Comment by Pyrdacor** [comment]
Patch 1.9.8 should fix this.
