### ISSUE TITLE
Crash: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#31]
About an hour into a game. Didn't seem to be caused by any user action. 

----------------------------------------------------------------------------

Index was outside the bounds of the array.

========== Stack Trace: ==========

   at Freeserf.Serf.HandleSerfStateKnightLeaveForWalkToFight()
   at Freeserf.Serf.Update()
   at Freeserf.Game.UpdateSerfs()
   at Freeserf.Game.UpdateVisuals()
   at Freeserf.Game.Update()
   at Freeserf.UI.Interface.Update()
   at Freeserf.LocalSpectatorViewer.Update()
   at Freeserf.Renderer.OpenTK.GameView.Render()
   at Freeserf.FreeserfForm.FrameTimer_Tick(Object sender, EventArgs e)

**Comment by Pyrdacor** [comment]
Hm this is strange as the mentioned code does not contain something which could cause the error. I will investigate on this.

**Comment by Pyrdacor** [comment]
Ok I found the problem but I need a bit time to find the root cause of it.

**Comment by Pyrdacor** [comment]
Patch 1.9.8 should fix this.
