### ISSUE TITLE
Crash: [serf]Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#43]
This one was after several hours of play. It looks like it occurred when a building was captured - that would be the enemy HQ. 

--------------------------------------------------------------------------------------------

[serf]Collection was modified; enumeration operation may not execute.

========== Stack Trace: ==========

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Freeserf.Collection`1.<GetEnumerator>d__11.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Freeserf.Building.BurnUp()
   at Freeserf.Game.DemolishBuilding(UInt32 pos)
   at Freeserf.Game.OccupyEnemyBuilding(Building building, UInt32 playerIndex)
   at Freeserf.Serf.HandleKnightOccupyEnemyBuilding()
   at Freeserf.Serf.Update()

[crash-28-03-19-02-39-27.zip](https://github.com/Pyrdacor/freeserf.net/files/3015998/crash-28-03-19-02-39-27.zip)

**Comment by Pyrdacor** [comment]
This is hopefully fixed in 1.9.10
