### ISSUE TITLE
Critical error: "[game][game]Failed to demolish flag with building"

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#58]
========== Stack Trace: ==========

<span style="font-size:70%">
   at Freeserf.Game.DemolishFlag(UInt32 pos)

   at Freeserf.Game.SurrenderLand(UInt32 pos)
   at Freeserf.Game.UpdateLandOwnership(UInt32 pos)
   at Freeserf.Building.BurnUp()
   at Freeserf.Game.DemolishBuilding(UInt32 pos)
   at Freeserf.Game.OccupyEnemyBuilding(Building building, UInt32 playerIndex)
   at Freeserf.Serf.HandleKnightOccupyEnemyBuilding()
   at Freeserf.Serf.Update()
</span>

..after red AI (Homen) conquered my castle.
[b1917-map3-3ai-game1-saves-plus-crashstate.zip](https://github.com/Pyrdacor/freeserf.net/files/3040691/b1917-map3-3ai-game1-saves-plus-crashstate.zip)
[log1_(b1.9.17).txt](https://github.com/Pyrdacor/freeserf.net/files/3040700/log1_.b1.9.17.txt)

**Comment by Pyrdacor** [comment]
Should be fixed in patch 1.9.18
