### ISSUE TITLE
Crash: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#63]
This occurred when demolishing a guard hut. I had recently captured it, but it was not under attack at the time I demolished it. 
It didn't offer me a save game.

---------------------------------------------------------------------------------------

Object reference not set to an instance of an object.

========== Stack Trace: ==========

   at Freeserf.Game.DemolishBuilding(UInt32 pos)
   at Freeserf.Game.DemolishBuilding(UInt32 pos, Player player)
   at Freeserf.UI.Interface.DemolishObject()
   at Freeserf.UI.PopupBox.HandleAction(Action action, Int32 x, Int32 y, Object tag)
   at Freeserf.UI.PopupBox.HandleButtonClick(Object buttonTag, Int32 x, Int32 y)
   at Freeserf.UI.PopupBox.PopupBox_ButtonClicked(Object sender, ClickEventArgs args)
   at Freeserf.UI.Button.HandleClickLeft(Int32 x, Int32 y)
   at Freeserf.UI.GuiObject.HandleEvent(EventArgs e)
   at Freeserf.UI.GuiObject.HandleEvent(EventArgs e)
   at Freeserf.UI.GuiObject.HandleEvent(EventArgs e)
   at Freeserf.UI.Interface.HandleEvent(EventArgs e)
   at Freeserf.LocalSpectatorViewer.SendEvent(EventArgs args)
   at Freeserf.UI.Gui.RenderView_Click(Object sender, EventArgs args)
   at Freeserf.Renderer.OpenTK.GameView.RunHandler(EventHandler handler, EventArgs args)
   at Freeserf.Renderer.OpenTK.GameView.NotifyClick(Int32 x, Int32 y, Button button)
   at Freeserf.FreeserfForm.ClickWaitTimer_Tick(Object sender, EventArgs e)

**Comment by Pyrdacor** [comment]
First in those cases you should now be able to save the game. The problem was that some user events (mouse clicks etc) did not provide the save option in contrast to game update crashes. Now also user event caused crashes will allow to save.

Second the bug should be fixed in patch 1.9.20.
